### ISSUE TITLE
Bug: Github oauth未正常工作

### ISSUE THREAD

**Issue by vlssu** [koishijs/koishi-plugin-github#1]

**Comment by shigma** [comment]
@MaikoTan 这个 issue 大概是怎么回事？

**Comment by MaikoTan** [comment]
> @MaikoTan 这个 issue 大概是怎么回事？

Idk, with the latest version now (5.0.2) I can only reproduce the error codes 422 and 408 in authorizing phase. (But I still am not able to make it work either, maybe not the same issue)
I would read some GitHub documents and investigate this issue later.

**Comment by MaikoTan** [comment]
https://github.com/koishijs/koishi-plugin-github/blob/44b5845c7db9a5cd0e06d6e9bc0337cfb4830102/src/server.ts#L120-L130

Looks like the code here requests the URL with query parameter instead of HTTP body, is it expected?

**Comment by shigma** [comment]
> Looks like the code here requests the URL with query parameter instead of HTTP body, is it expected?

I think I'm doing what the documentation says.

https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github

**Comment by MicroCBer** [comment]
As for my experience, if `config.redirect` is misconfigured, the api would be likely to return a 4xx error. Also, there seems not to be any configuration check here.

**Comment by colour93** [comment]
我也遇到了，无论是配置了 `config.redirect` 还是使用默认，都会出现如上问题，且最终绑定不成功

**Comment by postyizhan** [comment]
遇到同样问题

**Comment by SeeleVolleri** [comment]
koishi	4.17.7
koishi-plugin-github	5.5.1
2024-07-21 01:32:59 [W] github Error: Unprocessable Entity
                            at [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:335:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.request (/koishi/node_modules/koishi-plugin-github/lib/index.js:77:20)
                            at async Command.<anonymous> (/koishi/node_modules/koishi-plugin-github/lib/command.js:68:28)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1121:14)
                            at async Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1135:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2154:22
                            at async Proxy.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2057:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:860:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:860:16)
