### ISSUE TITLE
Bug: 无法使用部分重要功能

### ISSUE THREAD

**Issue by QianFuv** [koishijs/koishi-plugin-github#39]
仓库部分功能失效
```
2024-04-28 00:51:37 [W] github Error: Unprocessable Entity
                            at [cordis.invoke] (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\plugin-http\lib\index.cjs:331:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.request (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-github\lib\index.js:77:20)
                            at async Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-github\lib\command.js:68:28)
                            at async Array.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1149:14)
                            at async Command.execute (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1163:22)
                            at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2182:22
                            at async Proxy.withScope (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2085:22)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:16)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:16)
```
![image](https://github.com/koishijs/koishi-plugin-github/assets/111696321/373d6d35-2fd3-4aa8-8285-62eda17ee007)

**Comment by QianFuv** [comment]
Issue 相关功能也失效
```
2024-04-28 00:56:17 [W] github Error: Unprocessable Entity
                            at [cordis.invoke] (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\plugin-http\lib\index.cjs:331:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.request (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-github\lib\index.js:77:20)
                            at async Array.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1149:14)
                            at async Command.execute (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1163:22)
                            at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2182:22
                            at async Proxy.withScope (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2085:22)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:16)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:16)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:16)
```
![image](https://github.com/koishijs/koishi-plugin-github/assets/111696321/0a29ecfb-ec6e-4708-85bb-ccee3286e12a)

**Comment by QianFuv** [comment]
目前只有star是可用的

**Comment by QianFuv** [comment]
环境信息如下：
System:
    OS: Windows 10 10.0.20348
    CPU: (2) x64 Intel(R) Xeon(R) Platinum

Binaries:
    Node: 20.12.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.5
    Console: 5.28.4
    Koishi Desktop: 1.1.1

**Comment by PYLXU** [comment]
佬，您是如何解决的（？）

**Comment by QianFuv** [comment]
> 佬，您是如何解决的（？）

解决方法就是不用
