### ISSUE TITLE
无法添加仓库

### ISSUE THREAD

**Issue by Michaelwucoc** [koishijs/koishi-plugin-github#40]
```
 [W] github Error: Unprocessable Entity
                            at [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:340:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async GitHub.request (/koishi/node_modules/koishi-plugin-github/lib/index.js:77:20)
                            at async _Command.<anonymous> (/koishi/node_modules/koishi-plugin-github/lib/command.js:68:28)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1083:14)
                            at async _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1097:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2064:22
                            at async Proxy.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:1973:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:829:16)
                            at async Processor._handleMessage (/koishi/node_modules/@koishijs/core/lib/index.cjs:840:22)

```

**Comment by HydroGest** [comment]
相同的问题

**Comment by HydroGest** [comment]
设置 selfUrl
